import type { Translations } from "./en";

const te: Translations = {
  brand: { name: "హెల్త్‌ఫ్లో", tagline: "భారతదేశానికి సులభమైన ఆరోగ్యసేవ" },
  nav: { home: "హోమ్", hospitals: "ఆస్పత్రులు", doctors: "వైద్యులు", about: "మా గురించి", login: "లాగిన్", register: "నమోదు", logout: "లాగౌట్", dashboard: "డాష్‌బోర్డ్" },
  hero: { title: "సరైన చికిత్స, వేగంగా.", subtitle: "భారతదేశమంతటా ఆస్పత్రులు, వైద్యులను శోధించండి. ఒకే చోట అపాయింట్‌మెంట్‌లు, రికార్డులు.", ctaPrimary: "ఆస్పత్రి వెతకండి", ctaSecondary: "వైద్యుడిని వెతకండి", statsHospitals: "భాగస్వామ్య ఆస్పత్రులు", statsDoctors: "ధృవీకరించబడిన వైద్యులు", statsPatients: "సేవలు అందించిన రోగులు" },
  search: { placeholder: "ఆస్పత్రులు, వైద్యులను శోధించండి…", button: "శోధన" },
  features: { title: "మీకు కావలసినవన్నీ, ఒకే యాప్‌లో", f1Title: "ధృవీకరించబడిన ఆస్పత్రులు", f1Desc: "ప్రభుత్వ, ప్రైవేట్ & ట్రస్ట్ ఆస్పత్రులు.", f2Title: "బహుభాషా సేవ", f2Desc: "7 భారతీయ భాషలలో.", f3Title: "సురక్షిత రికార్డులు", f3Desc: "OTP లాగిన్‌తో పూర్తిగా రక్షితం.", f4Title: "రియల్-టైమ్ నవీకరణలు", f4Desc: "ప్రత్యక్ష OPD క్యూ, స్థితి." },
  portals: { title: "మీ పోర్టల్‌ను ఎంచుకోండి", subtitle: "మూడు సురక్షిత లాగిన్‌లు, ఒకే ప్లాట్‌ఫారమ్.", patient: "రోగి", patientDesc: "అపాయింట్‌మెంట్‌లు, రికార్డులు, చికిత్స.", doctor: "వైద్యుడు", doctorDesc: "OPD, ప్రిస్క్రిప్షన్‌లు.", admin: "ఆస్పత్రి అడ్మిన్", adminDesc: "విశ్లేషణ, పడకలు, ఫార్మసీ.", enter: "పోర్టల్‌ తెరువు" },
  auth: { loginTitle: "{{portal}} పోర్టల్‌లోకి సైన్ ఇన్", registerTitle: "{{portal}} ఖాతా సృష్టించండి", email: "ఇమెయిల్", password: "పాస్‌వర్డ్", fullName: "పూర్తి పేరు", phone: "మొబైల్ నంబర్", sendOtp: "ఇమెయిల్‌కు OTP పంపండి", otp: "6-అంకెల OTP", verifyOtp: "ధృవీకరించండి", or: "లేదా", continueGoogle: "Google తో కొనసాగించు", haveAccount: "ఇప్పటికే ఖాతా ఉందా?", noAccount: "ఖాతా లేదా?", signIn: "సైన్ ఇన్", signUp: "సైన్ అప్", submit: "కొనసాగించు", step1: "దశ 1: వివరాలు", step2: "దశ 2: OTP ధృవీకరణ", otpSentTo: "{{email}} కు OTP పంపబడింది", resendOtp: "OTP మళ్ళీ పంపండి", backToCredentials: "వెనక్కి", secureNotice: "2-దశల ధృవీకరణతో రక్షించబడింది" },
  patientReg: { dob: "పుట్టిన తేదీ", gender: "లింగం", male: "పురుషుడు", female: "స్త్రీ", other: "ఇతర", bloodGroup: "రక్త వర్గం", aadhaar: "ఆధార్ నంబర్ (12 అంకెలు)", aadhaarNote: "ఎన్‌క్రిప్ట్ చేయబడింది, చివరి 4 మాత్రమే కనిపిస్తాయి.", state: "రాష్ట్రం", district: "జిల్లా", city: "నగరం", pincode: "పిన్‌కోడ్", emergencyName: "అత్యవసర సంప్రదింపు పేరు", emergencyPhone: "అత్యవసర సంప్రదింపు ఫోన్" },
  doctorReg: { specialization: "నైపుణ్యం", qualification: "అర్హత (MBBS, MD…)", council: "మెడికల్ కౌన్సిల్ రిజి. నం.", experience: "సంవత్సరాల అనుభవం", fee: "సంప్రదింపు రుసుము (₹)", languages: "మాట్లాడే భాషలు (కామాతో)" },
  dashboard: { welcome: "తిరిగి స్వాగతం, {{name}}", yourId: "మీ ID", quickActions: "త్వరిత చర్యలు", bookAppt: "అపాయింట్‌మెంట్ బుక్", viewRecords: "రికార్డులు చూడు", payBills: "బిల్లు చెల్లించు", download: "ID కార్డ్ డౌన్‌లోడ్", upcoming: "రాబోయే", none: "ఏదీ షెడ్యూల్ లేదు", todayOpd: "నేటి OPD", activePatients: "క్రియాశీల రోగులు", pendingReports: "పెండింగ్ నివేదికలు", totalPatients: "మొత్తం రోగులు", todayRevenue: "నేటి ఆదాయం", bedsAvailable: "అందుబాటులోని పడకలు" },
  common: { loading: "లోడ్ అవుతోంది…", save: "సేవ్", cancel: "రద్దు", next: "తదుపరి", back: "వెనక్కి", error: "ఏదో తప్పు", success: "పూర్తయింది", requiredField: "ఇది అవసరం", invalidEmail: "చెల్లుబాటు అయ్యే ఇమెయిల్", invalidOtp: "6-అంకెల కోడ్" },
  hospitals: { title: "సమీపంలోని ఆస్పత్రులు", subtitle: "నైపుణ్యం, సౌకర్యాలు, బీమాతో ఫిల్టర్.", type: "రకం", speciality: "నైపుణ్యం", insurance: "బీమా", facilities: "సౌకర్యాలు", all: "అన్నీ", viewDetails: "వివరాలు చూడు", beds: "పడకలు", icu: "ICU", nicu: "NICU", rating: "రేటింగ్" },
  doctors: { title: "వైద్యుడిని వెతకండి", subtitle: "పేరు, నైపుణ్యం లేదా నగరంతో.", yearsExp: "సం. అనుభవం", bookAppt: "అపాయింట్‌మెంట్" },
  footer: { tagline: "భారతదేశంలోని ప్రతి మూలకు ఆరోగ్యసేవ.", company: "కంపెనీ", legal: "చట్టపరమైన", contact: "సంప్రదింపు", rights: "© {{year}} హెల్త్‌ఫ్లో. అన్ని హక్కులు ప్రత్యేకించబడ్డాయి." },
};
export default te;
