/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalsRouteImport } from './routes/portals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthPortalRouteImport } from './routes/auth.$portal'

const PortalsRoute = PortalsRouteImport.update({
  id: '/portals',
  path: '/portals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPortalRoute = AuthPortalRouteImport.update({
  id: '/auth/$portal',
  path: '/auth/$portal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portals': typeof PortalsRoute
  '/auth/$portal': typeof AuthPortalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portals': typeof PortalsRoute
  '/auth/$portal': typeof AuthPortalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portals': typeof PortalsRoute
  '/auth/$portal': typeof AuthPortalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/portals' | '/auth/$portal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/portals' | '/auth/$portal'
  id: '__root__' | '/' | '/portals' | '/auth/$portal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalsRoute: typeof PortalsRoute
  AuthPortalRoute: typeof AuthPortalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portals': {
      id: '/portals'
      path: '/portals'
      fullPath: '/portals'
      preLoaderRoute: typeof PortalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$portal': {
      id: '/auth/$portal'
      path: '/auth/$portal'
      fullPath: '/auth/$portal'
      preLoaderRoute: typeof AuthPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalsRoute: PortalsRoute,
  AuthPortalRoute: AuthPortalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
