/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalsRouteImport } from './routes/portals'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as HospitalsRouteImport } from './routes/hospitals'
import { Route as DoctorsSearchRouteImport } from './routes/doctors-search'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthPortalRouteImport } from './routes/auth.$portal'

const PortalsRoute = PortalsRouteImport.update({
  id: '/portals',
  path: '/portals',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsRoute = HospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsSearchRoute = DoctorsSearchRouteImport.update({
  id: '/doctors-search',
  path: '/doctors-search',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPortalRoute = AuthPortalRouteImport.update({
  id: '/auth/$portal',
  path: '/auth/$portal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/doctor': typeof DoctorRoute
  '/doctors-search': typeof DoctorsSearchRoute
  '/hospitals': typeof HospitalsRoute
  '/patient': typeof PatientRoute
  '/portals': typeof PortalsRoute
  '/auth/$portal': typeof AuthPortalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/doctor': typeof DoctorRoute
  '/doctors-search': typeof DoctorsSearchRoute
  '/hospitals': typeof HospitalsRoute
  '/patient': typeof PatientRoute
  '/portals': typeof PortalsRoute
  '/auth/$portal': typeof AuthPortalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/doctor': typeof DoctorRoute
  '/doctors-search': typeof DoctorsSearchRoute
  '/hospitals': typeof HospitalsRoute
  '/patient': typeof PatientRoute
  '/portals': typeof PortalsRoute
  '/auth/$portal': typeof AuthPortalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/doctor'
    | '/doctors-search'
    | '/hospitals'
    | '/patient'
    | '/portals'
    | '/auth/$portal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/doctor'
    | '/doctors-search'
    | '/hospitals'
    | '/patient'
    | '/portals'
    | '/auth/$portal'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/doctor'
    | '/doctors-search'
    | '/hospitals'
    | '/patient'
    | '/portals'
    | '/auth/$portal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DoctorRoute: typeof DoctorRoute
  DoctorsSearchRoute: typeof DoctorsSearchRoute
  HospitalsRoute: typeof HospitalsRoute
  PatientRoute: typeof PatientRoute
  PortalsRoute: typeof PortalsRoute
  AuthPortalRoute: typeof AuthPortalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portals': {
      id: '/portals'
      path: '/portals'
      fullPath: '/portals'
      preLoaderRoute: typeof PortalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals': {
      id: '/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof HospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors-search': {
      id: '/doctors-search'
      path: '/doctors-search'
      fullPath: '/doctors-search'
      preLoaderRoute: typeof DoctorsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$portal': {
      id: '/auth/$portal'
      path: '/auth/$portal'
      fullPath: '/auth/$portal'
      preLoaderRoute: typeof AuthPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DoctorRoute: DoctorRoute,
  DoctorsSearchRoute: DoctorsSearchRoute,
  HospitalsRoute: HospitalsRoute,
  PatientRoute: PatientRoute,
  PortalsRoute: PortalsRoute,
  AuthPortalRoute: AuthPortalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
